site_name: Tomasz Wlodarczyk WebPage
site_description: This is a personal website to share Science Tomasz is doing
site_author: I am a PhD student at the University of Arizona in the department of Environmental Science
site_url: https://TRwlodarczyk.github.io/githubTW

# Repository
repo_name: githubTW
repo_url: https://github.com/TRwlodarczyk/githubTW
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 - 2024'

# Configuration
theme:
  name: material
  highlightjs: true
  font:
    text: Roboto
    code: Regular

# Features  
features:
- navigation.instant
- navigation.tracking
- navigation.tabs
- navigation.tabs.sticky
- navigation.indexes
- navigation.top
- toc.follow

# 404 page
static_templates:
    - 404.html

# Search feature
include_search_page: false
search_index_only: true

# Theme Extras
extra_css:
  - stylesheets/extra.css
  
# Palette and theme (uses personalized colours)
language: en
palette:
    primary: custom
    accent: custom
icon:
    logo: material/cogs
    favicon: material/cogs

# Page tree
nav:
- Home: index.md
- Workshop materials:
    - 'Intro to Open Science': 00_basics.md
    - 'Project Management': 02_project_management.md
    - 'Managing Data': 03_managing_data.md
    - 'Documentation and Communication': 04_documentation_communication.md
    - 'Version Control': 05_version_control.md

# Extra Plugins
plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        ignore_h1_titles: True

# Extensions (leave as is)
markdown_extensions:
- admonition
- abbr
- attr_list
- def_list
- footnotes
- meta
- md_in_html
- toc:
    permalink: true
    title: On this page
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    repo_url_shorthand: true
    user: squidfunk
    repo: mkdocs-material
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.tabbed
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
